# 添付ファイル保存先の設定例
# storage.type: database|s3
storage:
  type: s3
  database:
    # database モード時に使用する LOB テーブル名
    lobTable: d_attachment
  s3:
    bucket: opendolphin-attachments
    region: ap-northeast-1
    endpoint: http://minio:9000
    basePath: clinics/${FACILITY_ID}/documents
    forcePathStyle: true
    serverSideEncryption: AES256
    kmsKeyId: null
    multipartUploadThresholdMb: 64
    lifecycle:
      transitionToStandardIaAfterDays: 30
      expireAfterDays: 3650
